Design: 로그인, 회원가입 모달 UI 구현
Do-it-Together-DoTo/DoTo_Front pull request #16
Opened 2024-05-05 15:52 UTC by ChaMinXD

## #️⃣연관된 이슈

> #10 

## 📝작업 내용

> 로그인 UI 구현
> 회원가입 모달 UI 구현

<br>

[🔥 **check your project preview here!**](https://doto-front-deploy.vercel.app/)

2024-05-05 16:04 UTC, mung96 approved these changes

2024-05-06 05:31 UTC, se-eun-park requested changes

2024-05-06 05:31 UTC, se-eun-park commented on src/router/Router.tsx
> +    },
```javascript
    {
      path: '/',
      children: [
        { index, element: <Navigate to="signup" /> },
        { path: 'signin', element: <SignIn /> },
        { path: 'signup', element: <SignUp /> },
        { path: 'findpw', element: <FindPw /> },
      ],
    },
```

2024-05-06 11:50 UTC, doreming16 approved these changes

2024-05-07 00:33 UTC, se-eun-park approved these changes
수고하셨습니다~

2024-05-07 00:34 UTC, merged