Design: Store Page UI 구현
Do-it-Together-DoTo/DoTo_Front pull request #27
Opened 2024-06-02 14:47 UTC by doreming16

## #️⃣ 연관된 이슈

> #12

## 📝 작업 내용
### 스토어/보관함 페이지 UI 구현
- 스토어: 캐릭터,아이템 / 보관함: 캐릭터, 아이템 총 4개 pages 분리 & 라우팅
- Main Profile은 세은 설정 따라서 Faker를 이용해 임의의 사용자 프로필 생성되는 상태
  - 랜덤 데이터에 따라 [이름, 레벨, 경험치, 코인 개수] 적용
- 기본 캐릭터, 아이템들은 더미로만 추가된 상태
  - isRare 값에 따라 특성장/(일반)성장 정도만 구분해서 띄움

## 💬 리뷰 요구사항(선택)
- 모달 UI는 background 없이 구성만 띄워서 확인했습니다(ShopCharacterPage)

2024-06-03 06:06 UTC, se-eun-park commented
![image](https://github.com/Do-it-Together-DoTo/DoTo_Front/assets/81418633/037dfa95-e3e3-49f7-b292-5a4de97d3942)

너비가 좀 안맞는 것 같습니다! 캡쳐화면 너비는 1920이긴 한데, 제 노트북으로 봐도 너비가 안맞아보였어요.

2024-06-03 06:49 UTC, se-eun-park reviewed
제 개인적인 생각인데,  `communityPage`는 모든 페이지가 다 다르게 생겨서 페이지들을 따로 만들어야 했지만` storePage`의 경우, 상단 타이틀과 안의 contents정도만 바뀌어서 페이지 하나로 관리가 가능할 것 같아요. 

모든 카테고리별 아이템, 캐릭터 페이지가 각자 있는건 리뷰하다보니 보기 힘들다고 느껴졌습니당. 당장 고칠건 아니고 나중에 리팩토링할 때, 고려해보면 좋을 것 같아요!

2024-06-03 06:49 UTC, se-eun-park commented on src/components/store/ShopCharacter.tsx
> +        <Coin className="w-[1.1875rem] h-[1.1875rem]"></Coin>
셀프 클로징태그 쓰면 좋을 것 같아용!

2024-06-03 06:49 UTC, se-eun-park commented on src/components/store/InventoryItem.tsx
> +      {props.isRare === true ? (
=== true 없어두 됩니당

2024-06-03 06:49 UTC, se-eun-park commented on src/components/store/InventoryItem.tsx
> +        <MagicPotion2 className="w-[3.8144rem] h-[3.8144rem] mb-[1rem]" />
나중엔 컴포넌트 네이밍 바꾸는게 좋을 것 같아요! 예를 들어, RarePotion, NormalPotion 정도로 바꾸면 더 알기 쉬울 것 같습니다.

2024-06-03 06:49 UTC, se-eun-park commented on src/pages/store/InventoryCharacterPage.tsx
> +import StoreMainProfile from '../../components/store/StoreMainProfile';
경로는 절대경로 설정해둔대로 사용하면 더 깔끔할 것 같습니당

2024-06-03 06:50 UTC, se-eun-park requested changes
우선은 store 페이지 간격 안맞는 것 수정해주시면 감사하겠습니다!

2024-06-03 07:06 UTC, doreming16 commented
+ 테스트 중 더미 아이템 들어간 블록에 스크롤 필요한 것 추가로 확인했습니다. 적용하고 커밋 올리겠습니다-!

2024-06-03 07:06 UTC, se-eun-park commented
![image](https://github.com/Do-it-Together-DoTo/DoTo_Front/assets/81418633/a9d56cd5-8439-42a2-a2b7-605a661ac15a)
 
너비는 잘 고쳐졌는데, 안에 카드들이 레이아웃 밖으로 튀어나와용,! 아직까진 저 레이아웃 넘어갈만큼 컨텐츠가 많진 않겠지만, 나중을 위해 스크롤로 넘어가는 정도는 추가해두는게 좋을 것 같아요

2024-06-04 23:55 UTC, doreming16 commented
item 들어있는 box 구역만 스크롤 가능하도록 변경했습니다 !

2024-06-06 08:31 UTC, se-eun-park approved these changes

2024-06-06 10:43 UTC, mung96 approved these changes

2024-06-07 10:59 UTC, ChaMinXD reviewed
고생

2024-06-08 06:58 UTC, merged